# permissions for end users to edit mypods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mypod-editor-role
rules:
- apiGroups:
  - harryyann.github.io
  resources:
  - mypods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harryyann.github.io
  resources:
  - mypods/status
  verbs:
  - get
